import { create } from 'zustand';
import type { Notification } from '../types';
import { backendApi } from '../services/api';

interface NotificationState {
  notifications: Notification[];
  smtpConfig: {
    enabled: boolean;
    senderEmail: string;
    appPassword?: string;
    recipientEmail: string;
  };
  isLoading: boolean;
  loadFromBackend: () => Promise<void>;
  addNotification: (title: string, message: string, type: 'warning' | 'info' | 'success') => void;
  markAsRead: (id: string) => void;
  updateSmtpConfig: (config: { enabled: boolean; senderEmail: string; appPassword?: string; recipientEmail: string }) => void;
}

export const useNotificationStore = create<NotificationState>((set) => ({
  notifications: [],
  smtpConfig: {
    enabled: true,
    senderEmail: '',
    appPassword: '',
    recipientEmail: '',
  },
  isLoading: false,

  loadFromBackend: async () => {
    set({ isLoading: true });
    try {
      const [notifs, smtp] = await Promise.all([
        backendApi.getNotifications(),
        backendApi.getSmtpConfig(),
      ]);
      set({
        notifications: notifs,
        smtpConfig: smtp || {
          enabled: true,
          senderEmail: '',
          appPassword: '',
          recipientEmail: '',
        },
        isLoading: false,
      });
    } catch (err: any) {
      console.warn('[NotificationStore] Backend offline, using defaults', err.message);
      set({ isLoading: false });
    }
  },

  addNotification: (title, message, type) => {
    const newNotif: Notification = {
      id: 'n_' + Date.now(),
      title,
      message,
      date: new Date().toISOString().split('T')[0],
      read: false,
      type,
    };
    set((state) => ({ notifications: [newNotif, ...state.notifications] }));
    // Ideally we would sync this to the backend if needed, but typically 
    // notifications are generated by the backend itself via cron jobs.
  },

  markAsRead: (id) => {
    set((state) => ({
      notifications: state.notifications.map((n) => (n.id === id ? { ...n, read: true } : n)),
    }));
    backendApi.markNotificationAsRead(id).catch(err => console.warn(err));
  },

  updateSmtpConfig: (config) => {
    set({ smtpConfig: config });
    backendApi.updateSmtpConfig(config).catch(err => console.warn(err));
  },
}));
